### ISSUE TITLE
ConcurrentModificationException during nextEntry

### ISSUE THREAD

**Issue by ChristopheLorenz** [xtreemfs/babudb#27]
I am using async with 4 worker threads, still when I insert records during a range query (in different threads), I often get hit by a ConcurrentModificationException :
```
java.util.ConcurrentModificationException
	at java.util.TreeMap$NavigableSubMap$SubMapIterator.nextEntry(TreeMap.java:1594)
	at java.util.TreeMap$NavigableSubMap$SubMapEntryIterator.next(TreeMap.java:1642)
	at java.util.TreeMap$NavigableSubMap$SubMapEntryIterator.next(TreeMap.java:1636)
	at org.xtreemfs.babudb.index.OverlayMergeIterator.getNextElement(OverlayMergeIterator.java:130)
	at org.xtreemfs.babudb.index.OverlayMergeIterator.next(OverlayMergeIterator.java:82)
	at org.xtreemfs.babudb.index.OverlayMergeIterator.next(OverlayMergeIterator.java:32)
	at org.xtreemfs.babudb.index.OverlayMergeIterator.getNextElement(OverlayMergeIterator.java:130)
	at org.xtreemfs.babudb.index.OverlayMergeIterator.next(OverlayMergeIterator.java:82)
	at org.xtreemfs.babudb.index.OverlayMergeIterator.next(OverlayMergeIterator.java:32)
	at eu.mikrosimage.messaging.storage.babuBase.testDirect.BabuDBConcurrentTest.testConcurrentRangeLookup(BabuDBConcurrentTest.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```
The database is then closed, so I can't even re-make the query.

I made a Junit test that reproduces the problem 100% of the time on my machine :

```
import java.io.File;
import java.util.Iterator;
import java.util.Map.Entry;

import junit.framework.TestCase;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.xtreemfs.babudb.BabuDBFactory;
import org.xtreemfs.babudb.api.BabuDB;
import org.xtreemfs.babudb.api.database.Database;
import org.xtreemfs.babudb.config.BabuDBConfig;
import org.xtreemfs.babudb.log.DiskLogger.SyncMode;
import org.xtreemfs.foundation.logging.Logging;
import org.xtreemfs.foundation.util.FSUtils;

public class BabuDBConcurrentTest extends TestCase
{
	public static final String baseDir = "test/";
	public static final int LOG_LEVEL = Logging.LEVEL_ERROR;
	public static final boolean MMAP = false;
	public static final boolean COMPRESSION = false;
	private static final int maxNumRecs = 16;
	private static final int maxBlockFileSize = 1024 * 1024 * 512;
	private BabuDB database;

	public BabuDBConcurrentTest()
	{
		Logging.start(LOG_LEVEL);
	}

	@Override
	@Before
	public void setUp() throws Exception
	{
		FSUtils.delTree(new File(baseDir));
	}

	@Override
	@After
	public void tearDown() throws Exception
	{
	}

	private static void insertSome(Database db, int start, int count)
	{
		int i = 0;
		while (i < count)
		{
			byte key[] = String.format("%09d", start + i).getBytes();
			System.out.println("Inserting " + (start + i));
			db.singleInsert(0, key, key, null);
			i++;
		}
	}

	@Test
	public void testConcurrentRangeLookup() throws Exception
	{
		BabuDBConfig cfg = new BabuDBConfig(baseDir, baseDir, 4, 0, 0, SyncMode.ASYNC, 0, 0, COMPRESSION, maxNumRecs,
				maxBlockFileSize, !MMAP, -1, LOG_LEVEL);
		database = BabuDBFactory.createBabuDB(cfg);
		final Database db = database.getDatabaseManager().createDatabase("test", 3);
		final int preInsertCount = 10;
		insertSome(db, 0, preInsertCount);
		Thread t = new Thread(new Runnable()
		{
			@Override
			public void run()
			{
				insertSome(db, preInsertCount, 10);
			}
		});
		t.start();

		String keyStart = String.format("%09d", 0);
		String keyEnd = String.format("%09d", 9999);
		Iterator<Entry<byte[], byte[]>> it = db.rangeLookup(0, keyStart.getBytes(), keyEnd.getBytes(), null).get();
		while (it.hasNext())
			System.out.println("Found " + new String(it.next().getKey()));
		t.join();
		database.shutdown();
	}

}

**Comment by chrkl** [comment]
Fixed by commit f2c1fc83bfb01b4884625262f7339bfc1eecbdbf. Thanks for your patch.
